#!/usr/bin/env bash
# checks if a host is on the network

if [ $1 ]
then
    ping -c 1 $1
    if [ $? -eq 0 ]
    then
        echo "UP"
    else
        echo "DOWN"
    fi
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi