#!/usr/bin/env bash
# checks if a host is on the network

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
else
    ping -c 5 $1 > /dev/null
    if [ $? -eq 0 ]; then
        echo "$1 is on the network"
    else
        echo "$1 is not on the network"
    fi
fi